export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    DASHBOARD: '/dashboard',
    WORKFLOWS: '/workflows',
    WORKFLOWS_CREATE: '/workflows/new',
    WORKFLOWS_EDIT: '/workflows/:id/edit',
    WORKFLOWS_DETAIL: '/workflows/:id',
    RUNS: '/runs',
    RUNS_DETAIL: '/runs/:id',
    TEMPLATES: '/templates',
    CONNECTORS: '/connectors',
    CONNECTORS_CREATE: '/connectors/create',
    CREDENTIALS: '/credentials',
    ALERTS: '/alerts',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    DOCS: '/docs',
    DOCS_GETTING_STARTED: '/docs/getting-started',
    DOCS_API: '/docs/api',
    DOCS_CONNECTORS: '/docs/connectors',
    DOCS_WORKFLOWS: '/docs/workflows',
    DOCS_FAQ: '/docs/faq',
    NOT_FOUND: '/404',
    TEST: '/test',
} as const;

