export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    WORKFLOWS: '/workflows',
    WORKFLOWS_CREATE: '/workflows/new',
    WORKFLOWS_EDIT: (id: string) => `/workflows/${id}/edit`,
    WORKFLOWS_DETAIL: (id: string) => `/workflows/${id}`,
    RUNS: '/runs',
    RUNS_DETAIL: (id: string) => `/runs/${id}`,
    TEMPLATES: '/templates',
    CONNECTORS: '/connectors',
    CREDENTIALS: '/credentials',
    SETTINGS: '/settings',
    DOCS: '/docs',
    DOCS_GETTING_STARTED: '/docs/getting-started',
    DOCS_API: '/docs/api',
    DOCS_CONNECTORS: '/docs/connectors',
    DOCS_WORKFLOWS: '/docs/workflows',
    DOCS_FAQ: '/docs/faq',
    NOT_FOUND: '/404',
} as const;

