# Generated by Django 6.0 on 2025-12-24 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_role_permission_rolepermission_role_permissions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'core_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('webhook', 'Webhook'), ('cron', 'Cron'), ('manual', 'Manual'), ('event', 'Event')], db_index=True, max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Trigger-specific configuration')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.workflow')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'db_table': 'core_trigger',
                'ordering': ['workflow', 'trigger_type'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('definition', models.JSONField(help_text='Workflow graph definition (nodes and edges)')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Version',
                'verbose_name_plural': 'Workflow Versions',
                'db_table': 'core_workflowversion',
                'ordering': ['workflow', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('webhook', 'Webhook'), ('cron', 'Cron'), ('event', 'Event')], default='manual', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict, help_text='Input data for the workflow run')),
                ('output_data', models.JSONField(blank=True, default=dict, help_text='Output data from the workflow run')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Key for idempotent runs', max_length=255)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_runs', to=settings.AUTH_USER_MODEL)),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.workflowversion')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'db_table': 'core_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(db_index=True, help_text='Step identifier from workflow definition', max_length=100)),
                ('step_type', models.CharField(help_text='Type of step (e.g., http, slack, llm)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('inputs', models.JSONField(blank=True, default=dict, help_text='Input data for this step')),
                ('outputs', models.JSONField(blank=True, default=dict, help_text='Output data from this step')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Execution order within the run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.run')),
            ],
            options={
                'verbose_name': 'Run Step',
                'verbose_name_plural': 'Run Steps',
                'db_table': 'core_runstep',
                'ordering': ['run', 'order', 'created_at'],
                'indexes': [models.Index(fields=['run', 'status'], name='core_runste_run_id_737a33_idx'), models.Index(fields=['run', 'order'], name='core_runste_run_id_c78a1a_idx'), models.Index(fields=['run', 'step_id'], name='core_runste_run_id_9553ff_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workspace', 'status'], name='core_workfl_workspa_ad1332_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['workspace', 'created_at'], name='core_workfl_workspa_40f7da_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['workflow', 'is_active'], name='core_trigge_workflo_4892aa_idx'),
        ),
        migrations.AddIndex(
            model_name='trigger',
            index=models.Index(fields=['trigger_type', 'is_active'], name='core_trigge_trigger_d854a1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'is_active'], name='core_workfl_workflo_b561b0_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'version_number'], name='core_workfl_workflo_4a376a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['workflow_version', 'status'], name='core_run_workflo_b4ad9a_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['workflow_version', 'created_at'], name='core_run_workflo_3b698a_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'created_at'], name='core_run_status_4b4dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['idempotency_key'], name='core_run_idempot_60c341_idx'),
        ),
    ]
