# Generated by Django 6.0 on 2025-12-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_error_suggestions'),
        ('core', '0012_custom_connectors'),
    ]

    operations = [
    ]
