# Generated by Django 6.0 on 2025-12-26 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_workflowpresence_core_workflowpresence_version_user_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='Unique identifier for the connector', max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('manifest', models.JSONField(help_text='Connector manifest definition')),
                ('icon_url', models.URLField(blank=True, help_text='URL to connector icon', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
                'db_table': 'core_connector',
                'ordering': ['display_name'],
            },
        ),
    ]
