# Generated by Django 6.0 on 2025-12-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_connector_connector_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='connector_type',
            field=models.CharField(choices=[('agent-tool', 'Agent Tool'), ('agent-model', 'Agent Model'), ('agent-memory', 'Agent Memory'), ('agent', 'Agent'), ('action', 'Action'), ('trigger', 'Trigger'), ('condition', 'Condition')], db_index=True, default='action', help_text='Type of connector (e.g., action, trigger, agent-tool)', max_length=20),
        ),
    ]
