# Generated by Django 6.0 on 2025-12-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_connector_connector_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customconnector',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon for the connector', null=True, upload_to='connector_icons/'),
        ),
    ]
