# Generated by Django 6.0 on 2025-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customconnector_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='icon_url',
            new_name='icon_url_dark',
        ),
        migrations.RemoveField(
            model_name='customconnector',
            name='icon',
        ),
        migrations.AddField(
            model_name='connector',
            name='icon_url_light',
            field=models.URLField(blank=True, help_text='URL to connector icon', null=True),
        ),
        migrations.AddField(
            model_name='customconnector',
            name='icon_url_dark',
            field=models.URLField(blank=True, help_text='URL to connector icon', null=True),
        ),
        migrations.AddField(
            model_name='customconnector',
            name='icon_url_light',
            field=models.URLField(blank=True, help_text='URL to connector icon', null=True),
        ),
    ]
