# Generated by Django 6.0 on 2026-01-04 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_icon_url_connector_icon_url_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The current working version being edited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.workflowversion'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this workflow is active and can be triggered'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='created_manually',
            field=models.BooleanField(default=False, help_text='Whether this version was manually created by user'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='version_label',
            field=models.CharField(blank=True, help_text="Optional label for manually created versions (e.g., 'Before refactor')", max_length=200),
        ),
    ]
