# Generated by Django 6.0 on 2026-01-09 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_migrate_versioning_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, help_text='Message role (user, assistant, or system)', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('actions', models.JSONField(blank=True, default=list, help_text='Structured actions returned by assistant (e.g., add_node, update_config)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (tokens, model, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'core_chatmessage',
                'ordering': ['thread', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for the conversation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation Thread',
                'verbose_name_plural': 'Conversation Threads',
                'db_table': 'core_conversationthread',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['trigger_type', 'status'], name='core_run_trigger_c728dd_idx'),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='workflow',
            field=models.OneToOneField(help_text='Workflow this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_thread', to='core.workflow'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(help_text='Conversation thread this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversationthread'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['workflow'], name='core_conver_workflo_ccbe98_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['updated_at'], name='core_conver_updated_b098bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='core_chatme_thread__105e18_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'role'], name='core_chatme_thread__18dc4d_idx'),
        ),
    ]
