# Generated by Django 6.0 on 2026-01-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatmsg_thread_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatmsg_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='core_chatmsg_created_at_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversationthread',
            name='core_convthread_workflow_idx',
        ),
        migrations.RemoveIndex(
            model_name='customconnector',
            name='core_customconn_workspace_idx',
        ),
        migrations.RemoveIndex(
            model_name='customconnector',
            name='core_customconn_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='customconnector',
            name='core_customconn_ws_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='customconnectorversion',
            name='core_customconnver_conn_idx',
        ),
        migrations.RemoveIndex(
            model_name='customconnectorversion',
            name='core_customconnver_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='run',
            name='core_run_wf_version_idx',
        ),
        migrations.RemoveIndex(
            model_name='run',
            name='core_run_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='run',
            name='core_run_created_at_desc_idx',
        ),
        migrations.RemoveIndex(
            model_name='trigger',
            name='core_trigger_workflow_idx',
        ),
        migrations.RemoveIndex(
            model_name='trigger',
            name='core_trigger_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='core_workflow_workspace_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='core_workflow_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='core_workflow_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='core_workflow_ws_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowversion',
            name='core_wfversion_workflow_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowversion',
            name='core_wfversion_is_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowversion',
            name='core_wfversion_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowversion',
            name='core_wfversion_wf_active_idx',
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this is the currently active thread for the workflow'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='workflow',
            field=models.ForeignKey(help_text='Workflow this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_threads', to='core.workflow'),
        ),
        migrations.AddIndex(
            model_name='conversationthread',
            index=models.Index(fields=['workflow', 'is_active'], name='core_conver_workflo_0509b6_idx'),
        ),
    ]
