# Generated by Django 6.0 on 2026-01-15 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_multiple_threads_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(db_index=True, help_text='Unique conversation identifier', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, help_text='Message role (user, assistant, or system)', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Agent Memory Message',
                'verbose_name_plural': 'Agent Memory Messages',
                'db_table': 'core_agentmemorymessage',
                'ordering': ['conversation_id', 'created_at'],
                'indexes': [models.Index(fields=['conversation_id', 'created_at'], name='core_agentm_convers_062061_idx'), models.Index(fields=['conversation_id', 'role'], name='core_agentm_convers_a6b378_idx')],
            },
        ),
    ]
